services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=magic
    networks:
      - planner_network
    ports:
      - "5432:5432"
    
  redis:
    image: redis:latest
    restart: always
    environment:
      - REDIS_PASSWORD=password
      - REDIS_USER=redis
      - REDIS_USER_PASSWORD=password
    networks:
      - planner_network
    ports:
      - "6379:6379"
    
  server:
    build: ./server
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/magic
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    networks:
      - planner_network
    ports:
      - "3000:3000"

  client:
    build: ./client
    environment:
      - VITE_SERVER_URL=http://localhost:3000/api
    depends_on:
      - server
    networks:
      - planner_network
    ports:
      - "4173:4173"

  proxy:
    build: ./nginx
    depends_on:
      - client
      - server
    networks:
      - planner_network
    ports:
      - "80:80"

networks:
  planner_network:
    driver: bridge