version: '3.9'

services:
  client:
    build: 
      context: .
      dockerfile: ./client/Dockerfile


  server:
    context: .
    dockerfile: ./server/Dockerfile

  db:
    image: postgres
    container_name: postgres_conteiner
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: magic
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  pgadmin4:
    image: elestio/pgadmin
    container_name: pgadmin_conteiner
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ya.ru
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      PGADMIN_LISTEN_PORT: 8080
    ports:
        - 8080:8080

  redis:
    image: redis:latest
    container_name: redis-container
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: password
      REDIS_USER: redis
      REDIS_USER_PASSWORD: password
    ports:
      - 6379:6379
